---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: quay.io/keycloak/keycloak
    newTag: 26.7.0@sha256:2eb3cd316835c990e69e26ade292ffa78f6fb0db7d5fc6377463c162e1979ac0
